require('dotenv').config();

export const {
  NIN_CHARGES,
  DRIVER_LICENSE,
  VIN_CHARGES,
  TIN_CHARGES,
  NUBAN_CHARGES,
  BASIC_PHONE_CHARGES,
  SELFIE_CHARGES,
  BVN_BASIC_CHARGES,
  ADVANCED_PHONE_CHARGES,
  PASSPORT_CHARGES,
  BVN_CHARGES,
  CAC_CHARGES,
  CAC_SHAREHOLDER,
  SELFIE_BVN_CHARGES,
  SELFIE_NIN_CHARGES,
  CHARGES,
} = process.env;
