FROM node:alpine As development

RUN apk update \
    && apk --no-cache --update add build-base 

RUN apk add --no-cache python3 py3-pip
RUN apk add --no-cache bash

WORKDIR /usr/src/app

COPY package*.json ./

RUN npm cache clean --force

RUN npm install

COPY . .

RUN npm run build auth

FROM node:alpine as production

ARG NODE_ENV=production
ENV NODE_ENV=${NODE_ENV}

WORKDIR /usr/src/app

COPY package*.json ./

RUN npm install --only=production

COPY . .

COPY --from=development /usr/src/app/dist ./dist

ARG PORT=5000
ENV PORT=$PORT
EXPOSE $PORT

CMD ["node", "dist/apps/auth/main"]