FROM node:alpine As development

RUN apk update \
    && apk --no-cache --update add build-base 

RUN apk add --no-cache python3 py3-pip

WORKDIR /usr/src/app

COPY package*.json ./

RUN npm install

COPY . .
COPY templates ./

RUN npm run build insight

COPY . ./dist
FROM node:alpine as production

ARG NODE_ENV=production
ENV NODE_ENV=${NODE_ENV}

WORKDIR /usr/src/app

COPY package*.json ./

RUN npm install --only=production

COPY . .

COPY --from=development /usr/src/app/dist ./dist

ARG PORT=3003
ENV PORT=$PORT
EXPOSE $PORT

CMD ["node", "dist/apps/insight/main"]